#!/usr/bin/env python3
"""Emit Table 2's unmasked-layer fractions from an artifact instead of from the manuscript (2026-09-02).

The layer counts live in evidence/factor_graph_metrics.json (ML-DSA 8 layers, ML-KEM 7); the
masked count is the RTL fact the manuscript documents at section 4.4 (masking_en_ctrl is constrained
to the first INTT layer only, ntt_ctrl.sv line 265) and is held here as an explicit, cited constant.

Fails closed if the artifact's layer counts move. Exactly one numeric token per value line.

Run:  python3 paper/arxiv/v3_correction_evidence/build_table2_layer_fractions.py
"""
import json, pathlib

REPO = pathlib.Path(__file__).resolve().parents[3]
m = json.loads((REPO / "evidence/factor_graph_metrics.json").read_text())["parameters"]
MASKED_LAYERS = 1   # ntt_ctrl.sv:265 -- masking_en_ctrl covers the first INTT layer only (source.md 4.4)
assert m["mldsa"]["layers"] == 8 and m["mlkem"]["layers"] == 7, m
out = ["# Table 2 layer fractions -- generated by build_table2_layer_fractions.py (2026-09-02)",
       "# layers from evidence/factor_graph_metrics.json; masked layers = 1 (ntt_ctrl.sv:265, cited at 4.4)", ""]
for alg in ("mldsa", "mlkem"):
    total = m[alg]["layers"]
    un = total - MASKED_LAYERS
    out += [f"{alg}_total_intt_layers = {total}",
            f"{alg}_unmasked_intt_layers = {un}",
            f"{alg}_unmasked_fraction = {100 * un / total:.1f}%"]
dest = REPO / "paper/arxiv/v3_correction_evidence/table2_layer_fractions.txt"
dest.write_text("\n".join(out) + "\n")
print("\n".join(out))
print(f"wrote {dest.relative_to(REPO)}")
