#!/usr/bin/env python3
"""Emit Exp B's published success-rate rows from the PRIMARY artifact (2026-09-02).

evidence/bkz_results.json holds 900 trial records over 20 (num_coefficients, block_size,
error_rate) arms. The manuscript's 4.8.2 table (source.md, section 4.8.2) reports ONE arm:
64 observed coefficients (16 radix-4 groups), block_size 2 (LLL-strength BKZ), at error rates
0 / 1 / 2 / 5 / 10 %. Earlier versions printed the 5 % row from a different arm (block_size 20,
30 trials, 1 success = 3 %); this file is the source for the corrected 6 % and for the arm
disclosure the manuscript now carries.

Fails closed if the arm does not have exactly 100 trials at 0-5 % and 50 at 10 %, if the record
count is not 900, or if the group geometry (256 coefficients = 64 groups x 4) does not hold.

Run:  python3 paper/arxiv/v3_correction_evidence/build_exp_b_published_rows.py
"""
import json, pathlib
from collections import defaultdict

REPO = pathlib.Path(__file__).resolve().parents[3]
ART = REPO / "evidence/bkz_results.json"
ARM_COEFFS, ARM_BLOCK = 64, 2
EXPECTED_TRIALS = {0.0: 100, 0.01: 100, 0.02: 100, 0.05: 100, 0.1: 50}

d = json.loads(ART.read_text())
recs = d["results"]
assert len(recs) == 900, f"expected 900 records, found {len(recs)}"
assert d["parameters"]["n"] == 256 and d["parameters"]["sub_dim"] == 64 and d["parameters"]["sub_problems"] == 4
agg = defaultdict(lambda: [0, 0])
for r in recs:
    key = (r["num_coefficients"], r["block_size"], r["error_rate"])
    agg[key][0] += 1
    agg[key][1] += int(bool(r["success"]))
    assert r["num_groups"] * 4 == r["num_coefficients"], r

out = ["# Exp B published rows -- generated by build_exp_b_published_rows.py (2026-09-02)",
       f"# source: {ART.relative_to(REPO)} ({len(recs)} records over {len(agg)} arms)",
       "# reported arm: 64 observed coefficients (16 groups of 4), block_size 2; success = exact recovery",
       "# Exactly one numeric token per value line.", "",
       f"exp_b_total_trials = {len(recs)}",
       f"exp_b_arm_coefficients = {ARM_COEFFS}",
       f"exp_b_arm_block_size = {ARM_BLOCK}",
       f"exp_b_groups_total = {256 // 4}",
       f"exp_b_group_size = 4",
       f"exp_b_arm_trials_per_rate = {EXPECTED_TRIALS[0.0]}",
       f"exp_b_arm_trials_at_10pct = {EXPECTED_TRIALS[0.1]}", ""]
for err, want_n in EXPECTED_TRIALS.items():
    n, k = agg[(ARM_COEFFS, ARM_BLOCK, err)]
    assert n == want_n, f"arm ({ARM_COEFFS},{ARM_BLOCK},{err}) has {n} trials, expected {want_n}"
    rate = round(100 * k / n)
    out.append(f"## error {err:.2f}: {k}/{n}")
    out.append(f"exp_b_success_at_{int(round(100 * err))}pct = {rate}%")
# the arm earlier versions mixed in, recorded for the historical record
n20, k20 = agg[(64, 20, 0.05)]
out += ["", f"## block_size-20 arm at 5% error (the arm v1-v2 printed as 3%): {k20}/{n20}",
        f"exp_b_bkz20_success_at_5pct = {round(100 * k20 / n20, 1)}%"]
dest = REPO / "paper/arxiv/v3_correction_evidence/exp_b_published_rows.txt"
dest.write_text("\n".join(out) + "\n")
print("\n".join(out))
print(f"wrote {dest.relative_to(REPO)}")
