#!/usr/bin/env python3
"""Emit the NC1 superseded-trial counts as LITERALS.

The manuscript reports the retracted NC1 result as a rate ("0/160"). That rate is
DERIVED -- it exists literally in no artifact. This script
computes it from the corpus and writes it down, so the literal cites committed output
rather than prose or a formula.

Regenerate:  python3 build_nc1_superseded_counts.py
"""
import json

SRC = "rederivation_results.json"
aggs = json.load(open(SRC))
if isinstance(aggs, dict):
    aggs = aggs.get("aggregates") or list(aggs.values())

nc1 = [a for a in aggs if a["config"].startswith("NC1-") and a.get("committed")]
trials = sum(a["committed"]["n_seeds"] for a in nc1)
fk = sum(round(a["committed"]["fk_rate"] * a["committed"]["n_seeds"]) for a in nc1)

assert nc1, "no NC1-* aggregates carry a superseded figure"
assert all(a["committed"]["fk_rate"] == 0.0 for a in nc1), "an NC1 committed fk_rate is non-zero"
assert trials == 160, f"NC1 superseded trial count is {trials}, not 160"
assert fk == 0, f"NC1 superseded full-key count is {fk}, not 0"

lines = [
    "# NC1 superseded (pre-correction) figures — generated by build_nc1_superseded_counts.py",
    f"# source: {SRC}   aggregates: {len(nc1)}",
    "",
    f"nc1_superseded_trials = {trials}",
    f"nc1_superseded_full_key = {fk}",
    f"nc1_superseded_rate = 0/160",
    "",
    "# per-aggregate breakdown (config, snr_n, trials, superseded fk_rate, re-derived fk_rate)",
]
for a in sorted(nc1, key=lambda x: x["config"]):
    c = a["committed"]
    lines.append(f"#   {a['config']:<30} {a['snr_n']:>7}  n={c['n_seeds']:<4} fk={c['fk_rate']}  redrv={a['full_key_rate']}")
open("nc1_superseded_counts.txt", "w").write("\n".join(lines) + "\n")
print("\n".join(lines))
