#!/usr/bin/env python3
"""Pool every Table 8 configuration that was run more than once at SNR*N=5,000 (2026-09-02).

Generalises build_table8_spread_pooled.py (which pools the L1+L3+L5+L7 row only) to the whole
table: a starred
row pools ALL of its committed runs at this budget, and its full-key count, Wilson 95% CI and
mean MI_BP are all computed over the same pooled per-seed records.

Sources are the committed pre-correction artifacts Table 8 is built from. Fails closed if any two
runs of one configuration share a seed, if any pooled seed sits outside the 30-iteration budget
or at another SNR*N, or if the spread row disagrees with the existing table8_spread_pooled.json.

Emits one numeric token per value line.

Run:  python3 paper/arxiv/v3_correction_evidence/build_table8_pooled_rows.py
"""
import json, math, pathlib

REPO = pathlib.Path(__file__).resolve().parents[3]
SRCS = {"evidence/ablation_results.json": "config", "evidence/ablation_tier123.json": "config",
        "evidence/all_k4_configs.json": "config_name", "evidence/nc4_validation.json": "config"}
SNR_N, BUDGET = 5000, 30
# Table 8 rows, keyed by observed-layer set -> printed label
TABLE8 = {(1,): "L1 only", (7,): "L7 only", (2, 4, 6): "L2+L4+L6 (no L1)", (5, 6, 7): "L5--L7",
          (1, 7): "L1+L7", (1, 2, 6, 7): "L1+L2+L6+L7", (1, 2, 5, 7): "L1+L2+L5+L7",
          (1, 4, 7): "L1+L4+L7", (1, 3, 4, 7): "L1+L3+L4+L7", (1, 3, 5, 7): "L1+L3+L5+L7 (spread)",
          (1, 2, 3, 4): "L1--L4 (consecutive)", (1, 2, 3, 4, 5): "L1--L5 (consecutive)",
          (1, 2, 3, 4, 5, 6): "L1--L6 (consecutive)", (1, 2, 3, 4, 5, 6, 7): "All (L1--L7)",
          (1, 2, 3, 7): "L1+L2+L3+L7", (1, 3, 5, 6): "L1+L3+L5+L6 (no L7)"}


def wilson(k, n, z=1.959963985):          # identical to build_table8_spread_pooled.py
    p = k / n
    den = 1 + z * z / n
    centre = (p + z * z / (2 * n)) / den
    half = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / den
    return 100 * (centre - half), 100 * (centre + half)


def pct(v):
    if v <= 0:
        return "0%"
    if v >= 100:
        return "100%"
    return f"{v:.1f}%"


runs = {}
for path, name_key in SRCS.items():
    for r in json.loads((REPO / path).read_text()):
        key = tuple(sorted(r["layers"]))
        if r["snr_n"] != SNR_N or key not in TABLE8:
            continue
        runs.setdefault(key, []).append((path, r[name_key], r["per_seed"]))

rows, out = [], []
out += ["# Table 8 pooled rows -- generated by build_table8_pooled_rows.py (2026-09-02)",
        "# every configuration with more than one committed run at SNR*N=5000 is pooled over ALL of",
        "# its runs; seed sets asserted pairwise disjoint; every seed asserted within the 30-iteration",
        "# budget; full-key = count of per-seed bsr == 1.0; Wilson 95% (z=1.959963985); MI = mean mi_bp.",
        "# Exactly one numeric token per value line.", ""]
for key, label in TABLE8.items():
    rs = runs.get(key, [])
    if len(rs) < 2:
        continue
    per = [p for _, _, ps in rs for p in ps]
    seeds = [p["seed"] for p in per]
    assert len(set(seeds)) == len(seeds), f"{label}: seed sets overlap -- NOT poolable"
    assert all(p["bp_iterations"] <= BUDGET for p in per), f"{label}: a seed exceeds the {BUDGET}-iteration budget"
    n = len(per)
    k = sum(1 for p in per if p["bsr"] == 1.0)
    lo, hi = wilson(k, n)
    mi = sum(p["mi_bp"] for p in per) / n
    tag = "row" + "ABCDEFGH"[len(rows)]   # digit-free tag so a value line holds exactly one numeric token
    rows.append({"label": label, "layers": list(key), "runs": [(p, nm, len(ps)) for p, nm, ps in rs],
                 "n": n, "k": k, "wilson_pct": [round(lo, 1), round(hi, 1)], "mean_mi_bp": round(mi, 2),
                 "mean_mi_bp_full": mi, "failing_seeds": [p["seed"] for p in per if p["bsr"] != 1.0]})
    out += [f"## {label}: runs " + " + ".join(f"{nm}[{len(ps)}]@{p.split('/')[-1]}" for p, nm, ps in rs),
            f"{tag}_full_key      {k}/{n}",
            f"{tag}_n             {n}",
            f"{tag}_wilson_lo_pct {pct(lo)}",
            f"{tag}_wilson_hi_pct {pct(hi)}",
            f"{tag}_mean_mi_bp    {mi:.2f}", ""]

# cross-check against the existing single-row builder's committed output
spread = next(r for r in rows if r["layers"] == [1, 3, 5, 7])
prev = json.loads((REPO / "paper/arxiv/v3_correction_evidence/table8_spread_pooled.json").read_text())
assert (spread["k"], spread["n"]) == (prev["n_full_key"], prev["n_seeds"]), "spread row disagrees with table8_spread_pooled.json"
assert abs(spread["mean_mi_bp_full"] - prev["mean_mi_bp_full"]) < 1e-9, "spread MI disagrees with table8_spread_pooled.json"

(REPO / "paper/arxiv/v3_correction_evidence/table8_pooled_rows.json").write_text(json.dumps(rows, indent=1) + "\n")
dest = REPO / "paper/arxiv/v3_correction_evidence/table8_pooled_rows.txt"
dest.write_text("\n".join(out) + "\n")
print("\n".join(out))
print(f"pooled rows: {len(rows)}   wrote {dest.relative_to(REPO)} and table8_pooled_rows.json")
