#!/usr/bin/env python3
"""Count the layer-ablation study's trials and configurations from the committed artifacts (2026-09-02).

Two corpora exist and the manuscript cites both:
  PRE-CORRECTION (Layer-0-only convergence check; the runs Table 8, the 35-subset sweep and Table 8b's
  NC1 arms are built from): evidence/{ablation_results,ablation_tier123,all_k4_configs,nc4_validation,
  nc1_moonshot_results,nc1_tier1_expansion_results}.json
  CORRECTED RE-DERIVATION (all-variable criterion): paper/arxiv/v3_correction_evidence/results.jsonl
Every count is over DISTINCT (layers, snr_n, seed) records, so a duplicated seed is never counted twice.

Emits the exact figures the manuscript prints (835 / 44 at 4.8.9, 635 / 276 and the 5--50 seed range for
the 35-subset sweep) and the floors it prints (800+ trials, 50+ configurations, 280+ targeted trials),
each floor asserted against the count that backs it. Fails closed if a floor is not met, if the sweep
is not exhaustive over the 35 four-layer subsets, or if any seed is duplicated inside a corpus.

Run:  python3 paper/arxiv/v3_correction_evidence/build_ablation_census.py
"""
import itertools, json, pathlib

REPO = pathlib.Path(__file__).resolve().parents[3]
V3 = REPO / "paper/arxiv/v3_correction_evidence"
AGG = ["evidence/ablation_results.json", "evidence/ablation_tier123.json", "evidence/all_k4_configs.json",
       "evidence/nc4_validation.json"]
RUN = ["evidence/nc1_moonshot_results.json", "evidence/nc1_tier1_expansion_results.json"]
TABLE8 = {(1,), (7,), (2, 4, 6), (5, 6, 7), (1, 7), (1, 2, 6, 7), (1, 2, 5, 7), (1, 4, 7), (1, 3, 4, 7),
          (1, 3, 5, 7), (1, 2, 3, 4), (1, 2, 3, 4, 5), (1, 2, 3, 4, 5, 6), (1, 2, 3, 4, 5, 6, 7), (1, 2, 3, 7),
          (1, 3, 5, 6)}
K4 = set(itertools.combinations(range(1, 8), 4))
FLOORS = {"trials": 800, "configs": 50, "targeted": 280}


def key(layers):
    return tuple(sorted(layers))


pre = set()
for f in AGG:
    for r in json.loads((REPO / f).read_text()):
        for p in r["per_seed"]:
            rec = (key(r["layers"]), r["snr_n"], p["seed"])
            assert rec not in pre, f"duplicate seed {rec} in {f}"
            pre.add(rec)
for f in RUN:
    for r in json.loads((REPO / f).read_text()):
        rec = (key(r["layers"]), r["snr_n"], r["seed"])
        assert rec not in pre, f"duplicate seed {rec} in {f}"
        pre.add(rec)
pre_configs = {k for k, _, _ in pre}
pre_5k_configs = {k for k, s, _ in pre if s == 5000}
cfg44 = TABLE8 | K4
assert len(cfg44) == 44, len(cfg44)
t8_sweep = {(k, s, sd) for k, s, sd in pre if s == 5000 and k in cfg44}
assert {k for k, _, _ in t8_sweep} == cfg44, "not every one of the 44 configurations has a trial"

# the exhaustive 35-subset sweep, raw
sweep = json.loads((REPO / "evidence/all_k4_configs.json").read_text())
assert {key(r["layers"]) for r in sweep} == K4, "sweep is not exhaustive over the 35 four-layer subsets"
assert all(r["snr_n"] == 5000 for r in sweep)
seeds_per = [r["n_seeds"] for r in sweep]
assert all(len(r["per_seed"]) == r["n_seeds"] for r in sweep)

# the corrected re-derivation of the same 35 subsets (results.jsonl, deduplicated)
corr = set()
for line in (V3 / "results.jsonl").read_text().splitlines():
    if line.strip():
        r = json.loads(line)
        corr.add((key(r["layers"]), r["snr_n"], r["seed"]))
corr_k4_5k = [c for c in corr if c[1] == 5000 and c[0] in K4]
corr_k4_sets = {c[0] for c in corr_k4_5k}
assert corr_k4_sets == K4, "corrected re-derivation does not cover all 35 subsets"

# Table 8b's targeted arms: the pre-correction NC1 runs plus the corrected NC1 / NC4-A / TOP-A runs
nc1_pre = [c for c in pre if c[1] >= 50000]
nc1_corr = [c for c in corr if c[1] >= 50000]   # NC1 arms, the 15 no-L1 sets at 50k, the gap topologies at 50k (TOP-A)
nc4a_corr = [c for c in corr if c[0] == (1, 4, 7) and c[1] == 5000]
targeted = len(nc1_pre) + len(nc1_corr) + len(nc4a_corr)

vals = {
    "layer_ablation_committed_trials": len(pre),
    "layer_ablation_committed_layer_sets": len(pre_configs),
    "layer_ablation_committed_layer_sets_at_5000": len(pre_5k_configs),
    "table8_and_sweep_trials": len(t8_sweep),
    "table8_and_sweep_configurations": len(cfg44),
    "sweep_trials": sum(seeds_per),
    "sweep_subsets": len(sweep),
    "sweep_seeds_min": min(seeds_per),
    "sweep_seeds_max": max(seeds_per),
    "sweep_corrected_rederivation_trials": len(corr_k4_5k),
    "targeted_archived_trials": targeted,
}
assert vals["layer_ablation_committed_trials"] >= FLOORS["trials"], vals
assert vals["layer_ablation_committed_layer_sets"] >= FLOORS["configs"], vals
assert vals["targeted_archived_trials"] >= FLOORS["targeted"], vals

out = ["# Layer-ablation census -- generated by build_ablation_census.py (2026-09-02)",
       "# distinct (layers, snr_n, seed) records; pre-correction corpus = evidence/*.json listed in the script;",
       "# corrected corpus = paper/arxiv/v3_correction_evidence/results.jsonl. Exactly one numeric token per value line.", ""]
out += [f"{k} = {v}" for k, v in vals.items()]
out += ["", "# floors the manuscript prints, each asserted against the count above it",
        f"layer_ablation_floor_trials = {FLOORS['trials']}",
        f"layer_ablation_floor_configurations = {FLOORS['configs']}",
        f"targeted_floor_trials = {FLOORS['targeted']}",
        "", "# Table 8b rows with NO archived run (F1-F4 at q=97): 60 trials, disclosed in the caption"]
dest = V3 / "ablation_census.txt"
dest.write_text("\n".join(out) + "\n")
print("\n".join(out))
print(f"wrote {dest.relative_to(REPO)}")
