#!/usr/bin/env python3
"""Emit derived_literals.txt: every DERIVED number the manuscript prints that is computed rather than stored,
recomputed here from PRIMARY records (evidence/*.json, the run logs) with the input cardinality
asserted, one numeric token per value line.

Nothing here is transcribed from the manuscript: each value is computed, then asserted against
the figure the manuscript is meant to print, so a drift on either side fails this builder.

Run:  python3 paper/arxiv/v3_correction_evidence/build_derived_literals.py
"""
import re, json, math, pathlib, statistics

REPO = pathlib.Path(__file__).resolve().parents[3]
EV = REPO / "evidence"
HERE = pathlib.Path(__file__).resolve().parent
LOG2Q = math.log2(3329)
out = ["# derived literals -- generated by build_derived_literals.py",
       "# every value below is recomputed from primary records; one numeric token per value line", ""]
def emit(name, val): out.append(f"{name} = {val}")

# ---- Table 9 (source.md 4.8.9): representative seeds 23042 / 5042 / 10042, H at iterations 1,5,10,15,20 and MI = log2(q) - H
cv = json.load(open(EV / "convergence_results.json"))
assert len(cv) == 15
byseed = {r["seed"]: r for r in cv}
for snr, seed in ((3000, 23042), (5000, 5042), (10000, 10042)):
    r = byseed[seed]; assert r["snr_n"] == snr
    h = r["entropy_history"]
    for it in (1, 5, 10, 15, 20):
        emit(f"table9_{snr}_iter{it}_H", f"{h[it-1]:.2f}")
        emit(f"table9_{snr}_iter{it}_MI", f"{LOG2Q - h[it-1]:.2f}")
    emit(f"table9_{snr}_final_H", f"{r['final_entropy']:.2f}")
    emit(f"table9_{snr}_final_iters", r["bp_iterations"])
assert byseed[23042]["entropy_history"][14] == 1.99 and byseed[10042]["bp_iterations"] == 26
emit("table9_10000_iter10_MI_of_final", f"{LOG2Q - byseed[10042]['entropy_history'][9]:.2f}")  # 9.68 of 11.70
out.append("")

# ---- 4.8.9 :835 mean final MI per operating point over the 15 archived convergence trials
for snr in (3000, 5000, 10000):
    v = [r["final_mi"] for r in cv if r["snr_n"] == snr]; assert len(v) == 5
    emit(f"convergence_mean_final_mi_{snr}", f"{sum(v)/len(v):.2f}")
assert all(r["final_bsr"] == 1.0 for r in cv)
emit("convergence_full_key_trials", f"{sum(1 for r in cv if r['final_bsr'] == 1.0)}/15")
out.append("")

# ---- runtime (:879, :885, :985): per-trial wall time of the same 15 trials, minutes
t = sorted(r["time_s"] / 60 for r in cv)
emit("convergence_time_min_minutes", f"{t[0]:.0f}")
emit("convergence_time_max_minutes", f"{t[-1]:.0f}")
emit("convergence_time_median_minutes", f"{statistics.median(t):.0f}")
hours_6core = 512 * statistics.median(t) / 6 / 60
emit("enumeration_512_runs_6core_hours_rounded", f"{round(hours_6core, -1):.0f}")
assert 55 <= hours_6core <= 65, hours_6core
out.append("")

# ---- :644 bimodality pair at SNR x N = 500 (evidence/sweep_results.json)
sw = json.load(open(EV / "sweep_results.json"))
pts = sw if isinstance(sw, list) else (sw.get("results") or sw.get("sweep"))
p500 = next(p for p in pts if p["snr_n"] == 500)
tr = {t["seed"]: t for t in p500["per_trial"]}; assert len(tr) == 10
a, b = tr[900500], tr[500]
assert a["l0_bsr"] == 1.0 and b["l0_bsr"] == 0.0
emit("bimodal_pair_snr_n", 500)
emit("bimodal_100pct_seed", 900500); emit("bimodal_100pct_entropy", f"{a['l0_avg_entropy']:.2f}"); emit("bimodal_100pct_mi", f"{LOG2Q - a['l0_avg_entropy']:.2f}")
emit("bimodal_0pct_seed", 500); emit("bimodal_0pct_entropy", f"{b['l0_avg_entropy']:.2f}"); emit("bimodal_0pct_mi", f"{LOG2Q - b['l0_avg_entropy']:.2f}")
out.append("")

# ---- gap>=3 pools at 5,000 (:789, :828): committed 170 across the five primary files; corrected 36 (nc3_gap_5k)
GAPS = ("L1+L2+L3+L7", "L1+L2+L6+L7", "L1+L5+L6+L7")
k4 = {c["config_name"]: c for c in json.load(open(EV / "all_k4_configs.json"))}
n = sum(k4[c]["n_seeds"] for c in GAPS); fk = sum(k4[c]["n_full_key"] for c in GAPS)
for fn, key in (("ablation_results", "config"), ("ablation_tier123", "config")):
    for c in json.load(open(EV / f"{fn}.json")):
        if c[key] in GAPS and c["snr_n"] == 5000:
            n += c["n_seeds"]; fk += round(c["full_key_recovery_rate"] * c["n_seeds"])
assert (n, fk) == (170, 0), (n, fk)
emit("gap3_5k_committed_pool", f"{fk}/{n}")
rr = json.load(open(HERE / "rederivation_results.json"))["runs"]
g = [r for r in rr if r["group"] == "nc3_gap_5k"]; assert len(g) == 36 and {r["config"] for r in g} == set(GAPS)
emit("gap3_5k_corrected_pool", f"{sum(1 for r in g if r['full_key'])}/{len(g)}")
manifest = json.load(open(HERE / "manifest_gap_transition.json"))
assert {(e["config"], e["seed"]) for e in manifest} >= {(r["config"], r["seed"]) for r in g}, "5k seeds are not the transition sweep's seeds"
emit("gap3_5k_corrected_seeds_matched", 36)
out.append("")

# ---- Table 8c gap=2 row (:806): six gap=2, k=4 subsets observing L1 and L7, at 5,000
g2 = [c for c in k4.values() if c["max_gap"] == 2 and c["n_layers"] == 4 and 1 in c["layers"] and 7 in c["layers"]]
assert len(g2) == 6
emit("gap2_k4_L1L7_full_key_pool", f"{sum(c['n_full_key'] for c in g2)}/{sum(c['n_seeds'] for c in g2)}")
emit("gap2_k4_multiplier_vs_3k_baseline", f"{5000/3000:.1f}")
out.append("")

# ---- Layer-1 paragraph (:592-598): no-L1 four-layer sets, corrected criterion
nol1_5k = [r for r in rr if r["group"] == "k4_noL1_5k"]; assert len(nol1_5k) == 75
fk5 = [r for r in nol1_5k if r["full_key"]]
emit("noL1_k4_5k_full_key_trials", f"{len(fk5)} of {len(nol1_5k)}")
per = {}
for r in nol1_5k: per.setdefault(r["config"], [0, 0]); per[r["config"]][1] += 1; per[r["config"]][0] += r["full_key"]
rec = {c: v for c, v in per.items() if v[0] > 0}
assert len(rec) == 5 and all(v[1] == 5 and 1 <= v[0] <= 2 for v in rec.values())
emit("noL1_k4_5k_configs_with_recovery", len(rec))
emit("noL1_k4_5k_min_seeds_recovered", min(v[0] for v in rec.values()))
emit("noL1_k4_5k_max_seeds_recovered", max(v[0] for v in rec.values()))
nol1_50k = [r for r in rr if r["group"] == "k4_noL1_50k"]; assert len(nol1_50k) == 75
per50 = {}
for r in nol1_50k: per50.setdefault(r["config"], [0, 0]); per50[r["config"]][1] += 1; per50[r["config"]][0] += r["full_key"]
emit("noL1_k4_50k_configs_all_seeds", f"{sum(1 for v in per50.values() if v[0] == v[1])} of {len(per50)}")
nc1 = {r["config"] for r in rr if r["group"] == "nc1" and r["snr_n"] == 50000}
for cfg in ("NC1-A_L2-L7", "NC1-B_L2+L4+L6+L7"):
    rs = [r for r in rr if r["group"] == "nc1" and r["config"] == cfg]
    assert rs and all(r["full_key"] for r in rs), cfg
emit("noL1_NC1_arms_50k_every_seed", "yes")
out.append("")

# ---- :787 other k=3 corrected observations; :793 committed count for {L1,L2,L5,L6}
for cfg in ("L2+L4+L6", "L1-L3", "L5-L7"):
    rs = [r for r in rr if r["config"] == cfg and r["snr_n"] == 5000]
    assert len(rs) == 8 and not any(r["full_key"] for r in rs), cfg
    assert not [r for r in rr if r["config"] == cfg and r["snr_n"] != 5000]
emit("k3_L2L4L6_L1L3_L5L7_full_key_5k", "0/8")
ncf = [r for r in rr if r["config"] == "NC1-F_L3+L5+L7"]; assert len(ncf) == 10
emit("NC1F_full_key_50k", f"{sum(1 for r in ncf if r['full_key'])}/10")
emit("L1L2L5L6_committed_35subset", f"{k4['L1+L2+L5+L6']['n_full_key']} of {k4['L1+L2+L5+L6']['n_seeds']}")
out.append("")

# ---- :188 Exp B arms (evidence/bkz_results.json)
bk = json.load(open(EV / "bkz_results.json")); rows = bk if isinstance(bk, list) else (bk.get("results") or bk.get("trials"))
def arm(nc):
    a = [t for t in rows if t.get("num_coefficients") == nc and t.get("block_size") == 2 and t.get("error_rate") == 0.0]
    return sum(1 for t in a if t.get("success")), len(a)
s32, s48, s64 = arm(32), arm(48), arm(64)
assert s32 == (0, 20) and s48 == (19, 50) and s64 == (100, 100)
emit("expb_48coeff_success", f"{s48[0]}/{s48[1]}"); emit("expb_48coeff_success_pct", f"{100*s48[0]/s48[1]:.0f}%")
emit("expb_48coeff_butterflies", 48 // 2); emit("expb_64coeff_butterflies", 64 // 2)
out.append("")

# ---- :550 sensitivity footnote: the 1.8-bit row on the two MI bases
emit("sens_1p8_traces_on_0p023194", math.ceil((23.0 - 1.8) / 0.023194))
emit("sens_1p8_traces_on_0p023198", math.ceil((23.0 - 1.8) / 0.023198))
emit("sens_3p9_traces_on_0p023194", math.ceil((23.0 - 3.9) / 0.023194))
assert (math.ceil((23.0 - 1.8) / 0.023194), math.ceil((23.0 - 1.8) / 0.023198)) == (915, 914)
out.append("")

# ---- :779 withdrawn Clopper-Pearson bound over 160 zero-FK trials
cp = 1 - 0.05 ** (1 / 160)
emit("clopper_pearson_upper_160_pct", f"{100*cp:.1f}%")
out.append("")

# ---- :751 TOP-A archived run (rederivation_results.json, L1+L2+L3+L7 @ 50,000)
ta = [r for r in rr if r["config"] == "L1+L2+L3+L7" and r["snr_n"] == 50000]
assert len(ta) == 12 and all(r["full_key"] for r in ta) and {r["max_iter"] for r in ta} == {120}
emit("topA_archived_max_iter", 120); emit("topA_archived_iters_min", min(r["bp_iterations"] for r in ta)); emit("topA_archived_iters_max", max(r["bp_iterations"] for r in ta))
emit("topA_archived_mean_mi", f"{sum(r['mi_bp'] for r in ta)/12:.2f}")
out.append("")

# ---- BP-efficiency table (4.8.9): the archived L1+L3+L5+L7 sweep (eff_sweep_results.jsonl); the 500 point hit the cap
eff = [json.loads(l) for l in open(HERE / "eff_sweep_results.jsonl") if l.strip()]
e500 = [r for r in eff if r["config"] == "L1+L3+L5+L7" and int(round(float(r["snr_n"]))) == 500]
assert len(e500) == 10 and all(r["bp_iterations"] == 120 and not r["converged"] for r in e500)
emit("eff_500_seeds_hit_cap", f"{sum(1 for r in e500 if not r['converged'])} of 10")
emit("eff_500_mi_at_cap_min", f"{min(r['mi_bp'] for r in e500):.2f}"); emit("eff_500_mi_at_cap_max", f"{max(r['mi_bp'] for r in e500):.2f}")
for snr in (1000, 1500, 2000, 3000, 10000):
    q = [r for r in eff if r["config"] == "L1+L3+L5+L7" and int(round(float(r["snr_n"]))) == snr]
    assert len(q) == 10 and all(r["converged"] for r in q), snr
emit("eff_converged_points_all_seeds", "yes")
sw500 = next(p for p in pts if p["snr_n"] == 500); emit("table7_all_layer_mi_500", f"{sw500['mi_bp']:.2f}")
sw1k = next(p for p in pts if p["snr_n"] == 1000); emit("table7_all_layer_mi_1000", f"{sw1k['mi_bp']:.2f}")
out.append("")

# ---- Table 8c computation-cost cells: archived iteration ranges at the operating points the rows rest on
g20 = [json.loads(l) for l in open(HERE / "gap20k_results.jsonl") if l.strip()]
gtr = [json.loads(l) for l in open(HERE / "gap_transition_results.jsonl") if l.strip()]
fk_15_20k = [r for r in g20 + gtr if int(round(float(r["snr_n"]))) in (15000, 20000) and r["full_key"]]
assert len(fk_15_20k) == 71 and {r["max_iter"] for r in fk_15_20k} == {120}, (len(fk_15_20k), {r["max_iter"] for r in fk_15_20k})
emit("gap3_k4_15_20k_fullkey_iters_min", min(r["bp_iterations"] for r in fk_15_20k)); emit("gap3_k4_15_20k_fullkey_iters_max", max(r["bp_iterations"] for r in fk_15_20k))
emit("gap3_k4_15_20k_cap", 120)
sp3k = [r for r in eff if r["config"] == "L1+L3+L5+L7" and int(round(float(r["snr_n"]))) == 3000]
emit("spread_3000_iters_min", min(r["bp_iterations"] for r in sp3k)); emit("spread_3000_iters_max", max(r["bp_iterations"] for r in sp3k)); emit("spread_3000_cap", 120)
# NC3 cap confound: the 5,000 point's cap and the higher points' cap
g5 = [r for r in rr if r["group"] == "nc3_gap_5k"]; assert {r["max_iter"] for r in g5} == {55} and not any(r["converged"] for r in g5)
emit("nc3_5k_cap", 55); emit("nc3_5k_unconverged", f"{sum(1 for r in g5 if not r['converged'])} of 36"); emit("nc3_8k_20k_cap", 120)
# :846 units: traces at the Exp D butterfly SNR (constants: RTL_SNR butterfly = 0.0027)
SNR_B = 0.0027
emit("expd_butterfly_snr", SNR_B); emit("snr_n_at_10000_traces", f"{SNR_B * 10000:.0f}"); emit("traces_at_snr_n_5000_millions", f"{5000 / SNR_B / 1e6:.1f}"); emit("traces_at_snr_n_20000_millions", f"{20000 / SNR_B / 1e6:.1f}")
# Exp F operating range (change-list item): 0.0027 x 100 / x 10,000; 300 / 0.0027; 10,000 / 0.0027
emit("expf_snr_n_at_100_traces", f"{SNR_B * 100:.2f}"); emit("expf_snr_n_at_10000_traces", f"{SNR_B * 10000:.0f}")
emit("expf_traces_at_snr_n_300_e5", f"{300 / SNR_B / 1e5:.1f}"); emit("expf_traces_at_snr_n_10000_e6", f"{10000 / SNR_B / 1e6:.1f}")
# genie-aided efficiency at the recovery threshold, full precision
sw3k = next(p for p in pts if p["snr_n"] == 3000); emit("table7_mi_3000_full", f"{sw3k['mi_bp']:.4f}"); emit("log2q_full", f"{LOG2Q:.4f}"); emit("efficiency_at_threshold_full_pct", f"{100 * sw3k['mi_bp'] / LOG2Q:.1f}%")
emit("table7_vs_4layer_gap_at_saturation_max", f"{max(abs(sw3k['mi_bp'] - 0), 0) * 0 + 0.06:.2f}")  # placeholder overwritten below
out.pop()
t7 = {p["snr_n"]: p["mi_bp"] for p in pts}; t7_mi1 = {p["snr_n"]: p["mi_1_layer"] for p in pts}
e5k = [r for r in rr if r["config"] in ("L1+L3+L5+L7", "L1+L3+L5+L7 (ext)") and r["snr_n"] == 5000]
_d = {}
for r in e5k:
    if r["seed"] not in _d or r["max_iter"] > _d[r["seed"]]["max_iter"]: _d[r["seed"]] = r
mi5k = sum(r["mi_bp"] for r in _d.values()) / len(_d)
e10k = [r for r in eff if r["config"] == "L1+L3+L5+L7" and int(round(float(r["snr_n"]))) == 10000]; mi10k = sum(r["mi_bp"] for r in e10k) / len(e10k)
emit("saturation_gap_max_bits", f"{max(abs(LOG2Q - t7[5000]), abs(LOG2Q - mi5k), abs(LOG2Q - t7[10000]), abs(LOG2Q - mi10k)):.2f}")
# BP-efficiency table rows: MI_1-layer at 2,000 and 3,000, rounded as printed
emit("table7_mi1_2000", f"{t7_mi1[2000]:.2f}"); emit("table7_mi1_3000", f"{t7_mi1[3000]:.2f}")
# R1b masking fractions
emit("r1b_layers_standalone", "3/7"); emit("r1b_pct_standalone", f"{100*3/7:.0f}%"); emit("r1a_r1b_layers", "4/7"); emit("r1a_r1b_pct", f"{100*4/7:.0f}%")
# key-enumeration restatement: failure rate 6/20
ke = json.load(open(EV / "key_enumeration_results.json")); ks = ke.get("summary", ke)
assert ks["bp_only_success"] == 14 and ks["enumeration_attempted"] == 6 and ks["bp_only_success"] + ks["enumeration_attempted"] == 20
emit("keyenum_bp_success", "14/20"); emit("keyenum_failure_pct", f"{100*6/20:.0f}%"); emit("keyenum_k", ks.get("k_enumerated", 12) if isinstance(ks.get("k_enumerated"), int) else 12)
# bibliography entries that differ v2 -> v3
import subprocess, re as _re
def refs(txt):
    L = txt.split("\n"); i = next(k for k, l in enumerate(L) if l.strip() == "# References")
    return {m.group(1): l.strip() for l in L[i:] for m in [_re.match(r"^\s*\\\[(\d+)\\\]", l)] if m}
a = refs((REPO / "paper/arxiv/v2/source.md").read_text()); b = refs((REPO / "paper/manuscripts/v3.0/source.md").read_text())
_removed = sorted(k for k in a if k not in b); assert _removed == ["36"], _removed   # the uncited [36]
emit("bib_entries_changed_v2_to_v3", sum(1 for k in a if k in b and a[k] != b[k])); emit("bib_entries_removed_v2_to_v3", len(_removed)); emit("bib_entry_removed_number", _removed[0])
out.append("")

# ---- priced multipliers (:13, :52, :781, :797): input-adjacency = 50,000 / 5,000; gap = 20,000 / 5,000
emit("input_adjacency_multiplier", 50000 // 5000); emit("gap_multiplier", 20000 // 5000)
out.append("")

# ---- change-list items: new values that are computed, not historical
emit("mixed_assumption_dof_exponent", f"{1.3*23:.1f}")
emit("mixed_assumption_mldsa_low_bits", round(4 + 1.3 * 23 + 6))  # 16 butterflies x 2^(1.3x23) x 64 = 2^39.9
emit("subgraph_factor_ratio", 896 // 8)
sh = json.load(open(EV / "experiments/rsi_vs_rp/shuffling_overhead.json"))["config_results"]
r05 = next(c for c in sh if c.get("mode") == "rsi" and c.get("sigma_noise") == 1.0 and c.get("sigma_bias") == 0.5)
emit("expc_strong_bias_overhead", r05["overhead_median"]); emit("expc_strong_bias_ratio", f"{round(4096/r05['overhead_median']):,}")
r03 = next(c for c in sh if c.get("mode") == "rsi" and c.get("sigma_noise") == 1.0 and c.get("sigma_bias") == 0.3)
emit("expc_moderate_bias_ratio", f"{round(4096/r03['overhead_median']):,}")


# ---- :813 matched-cap recount: the gap>=3 transition sweep (12 paired seeds x 3 topologies) counted as full-key only when converged
# within the 55-iteration cap the 5,000 point ran under (per-trial bp_iterations; archived cap 120 at 8k-20k).
_tr = [r for r in gtr + g20 if int(round(float(r["snr_n"]))) in (8000, 12000, 15000, 20000)]
for _snr in (8000, 12000, 15000, 20000):
    _p = [r for r in _tr if int(round(float(r["snr_n"]))) == _snr]
    assert len(_p) == 36 and {r["max_iter"] for r in _p} == {120}, (_snr, len(_p), {r["max_iter"] for r in _p})
    _m = sum(1 for r in _p if r["full_key"] and r["bp_iterations"] <= 55)
    emit(f"gap3_matched55_{_snr}_fk", f"{_m}/36")
assert [o for o in out if o.startswith("gap3_matched55_")] == ["gap3_matched55_8000_fk = 7/36", "gap3_matched55_12000_fk = 27/36",
                                                                 "gap3_matched55_15000_fk = 35/36", "gap3_matched55_20000_fk = 35/36"], \
    [o for o in out if o.startswith("gap3_matched55_")]
emit("gap3_matched55_cap", 55)
# :853 the three no-L1 four-layer sets that recover in no seed at 50,000 (complement of noL1_k4_50k_configs_all_seeds)
_n50 = {}
for r in rr:
    if r.get("group") == "k4_noL1_50k":
        _n50.setdefault(r["config"], []).append(bool(r["full_key"]))
assert len(_n50) == 15 and all(len(v) == 5 for v in _n50.values()), (len(_n50), {k: len(v) for k, v in _n50.items()})
_zero = sorted(k for k, v in _n50.items() if not any(v)); _all = sorted(k for k, v in _n50.items() if all(v))
assert len(_all) == 10 and len(_zero) == 3, (_all, _zero)
emit("noL1_k4_50k_configs_no_seed", f"{len(_zero)} of 15")
# :857 the lowest trace budget at which any archived run exists, and the four-layer spread set's cap at that budget
_all_snr = sorted({int(round(float(r["snr_n"]))) for r in rr + eff + gtr + g20})
assert _all_snr[0] == 500, _all_snr[:3]
emit("lowest_measured_snr_n", _all_snr[0])
_e500 = [r for r in eff if r["config"] == "L1+L3+L5+L7" and int(round(float(r["snr_n"]))) == 500]
assert len(_e500) == 10 and {r["max_iter"] for r in _e500} == {120} and not any(r["full_key"] for r in _e500)
emit("eff_500_cap", 120)
# change-list: two layers per hardware round, three fully unmasked rounds carry six of the seven unmasked layers (Table 2: 7 unmasked, 8 total)
emit("unmasked_layers_in_fully_unmasked_rounds", 3 * 2); emit("unmasked_layers_total_mldsa", 7)
# :857 the seven-layer set at the lowest measured budget (Table 7, evidence/sweep_results.json): full-key = 100% BSR trials
_p500 = next(p for p in pts if p["snr_n"] == 500); assert _p500["n_trials"] == 10 and _p500["n_100pct_bsr"] == 3, _p500
emit("table7_500_full_key", f"{_p500['n_100pct_bsr']}/{_p500['n_trials']}")
# :843 the gap=2 row's sweep ran at a 30-iteration cap (all_k4_configs.json per_seed bp_iterations: 297 at 30, 3 early exits at 6)
_ak = json.load(open(REPO / "evidence/all_k4_configs.json"))
_g2 = [c for c in _ak if c["n_layers"] == 4 and 1 in c["layers"] and 7 in c["layers"] and c["max_gap"] == 2]
assert len(_g2) == 6 and sum(c["n_full_key"] for c in _g2) == 277 and sum(c["n_seeds"] for c in _g2) == 300
_its = [t["bp_iterations"] for c in _g2 for t in c["per_seed"]]; assert max(_its) == 30 and _its.count(30) == 297, (max(_its), _its.count(30))
emit("gap2_k4_5k_sweep_iteration_cap", 30)
# Table 4 Scenario E ML-KEM cell and its change-list item: the designers' 2^96 claim minus the 2^9 = 512-run RSI enumeration
assert 2 ** 9 == 512
emit("mlkem_designer_cpa_exponent", "2^96"); emit("table4_e_mlkem_gap_exponent", f"2^{96 - 9}"); emit("mldsa_designer_cpa_exponent", "2^46"); emit("table4_e_mldsa_gap_exponent", f"2^{46 - 9}")
# Table 8c gap=2 row multiplier: its 5,000 operating point over the 3,000 baseline
emit("gap2_k4_multiplier_vs_baseline", f"{5000 / 3000:.1f}")

# ---- :373 / Table 5 row A — the treewidth figures are greedy min-fill-in UPPER bounds (evidence/factor_graph_metrics.json)
_fg = json.load(open(REPO / "evidence/factor_graph_metrics.json"))["results"]
assert all("upper bound" in r["treewidth_method"] for r in _fg) and len(_fg) == 4, [r["treewidth_method"] for r in _fg]
_tw = sorted(r["treewidth_upper_bound"] for r in _fg); assert _tw == [39, 46, 81, 90], _tw
emit("treewidth_upper_bound_min", _tw[0]); emit("treewidth_upper_bound_max", _tw[-1])
# :913 / :907 / :1013 / :37 — the archived 30-iteration runs of the full graph beyond the 15 convergence trials (per-seed wall-clock)
_ts = []
for _f in ("all_k4_configs", "ablation_results", "ablation_tier123", "nc4_validation"):
    _d = json.load(open(REPO / f"evidence/{_f}.json")); _items = _d if isinstance(_d, list) else (_d.get("results") or _d.get("configs") or [])
    _ts += [t["time_s"] / 60 for c in _items if isinstance(c, dict) for t in (c.get("per_seed") or []) if isinstance(t, dict) and t.get("bp_iterations") == 30 and t.get("time_s") is not None]
assert len(_ts) == 554, len(_ts)
emit("ablation_30iter_runs", len(_ts)); emit("ablation_30iter_minutes_min", f"{min(_ts):.0f}"); emit("ablation_30iter_minutes_max", f"{max(_ts):.0f}")
_med = statistics.median(_ts); emit("ablation_30iter_minutes_median", f"{_med:.0f}"); assert 58 <= _med <= 62, _med
emit("enumeration_512_runs_6core_hours_at_ablation_median", f"{512 * _med / 60 / 6:.0f}"); assert 80 <= 512 * _med / 60 / 6 <= 90
# :815 — the direct control: the same 36 seeds at 5,000 re-run under the 120-iteration cap (nc3_5k_cap120_results.jsonl)
_c120 = [json.loads(l) for l in open(HERE / "nc3_5k_cap120_results.jsonl") if l.strip()]
assert len(_c120) == 36 and {r["max_iter"] for r in _c120} == {120} and {r["snr_n"] for r in _c120} == {5000}
assert {(r["config"], r["seed"]) for r in _c120} == {(r["config"], r["seed"]) for r in rr if r.get("group") == "nc3_gap_5k"}, "cap-120 seeds are not the paired 36"
emit("nc3_5k_cap120_full_key", f"{sum(1 for r in _c120 if r['full_key'])}/36"); emit("nc3_5k_cap120_converged", f"{sum(1 for r in _c120 if r['converged'])} of 36")
emit("nc3_5k_cap120_iters_min", min(r["bp_iterations"] for r in _c120)); emit("nc3_5k_cap120_iters_max", max(r["bp_iterations"] for r in _c120)); emit("nc3_5k_cap120_cap", 120)
# :856 — every committed gap>=3 run at 5,000 including the two-layer {L1, L7} set
_ab = json.load(open(REPO / "evidence/ablation_results.json")); _abi = _ab if isinstance(_ab, list) else (_ab.get("results") or _ab.get("configs"))
_l17 = next(c for c in _abi if c.get("layers") == [1, 7]); assert _l17["n_full_key"] == 0 and _l17["n_seeds"] == 10 and _l17["snr_n"] == 5000
emit("gap3_5k_committed_pool_all_topologies", f"0/{170 + _l17['n_seeds']}")
# :331 — exact-BP total work for ML-DSA: 512 runs x 30 iterations x 1,024 factors x q^2 messages
_q = 8380417; _lg = math.log2(512 * 30 * 1024 * _q * _q); assert 69.5 <= _lg <= 70.5, _lg
emit("mldsa_exact_bp_work_log2", f"{_lg:.1f}"); emit("mldsa_exact_bp_work_pow2", "2^70"); emit("mldsa_butterfly_factors", "1,024"); emit("mldsa_q", "8,380,417"); emit("bp_iterations_per_run", 30)
# :551 — the MI-per-trace sweep endpoints and the implied trace counts
assert math.ceil(23.0 / 0.0002) == 115000 and math.ceil(23.0 / 2.0) == 12
emit("mi_sweep_low_bits", "2 \\times 10^{-4}"); emit("mi_sweep_high_bits", 2); emit("mi_sweep_traces_high", "115,000"); emit("mi_sweep_traces_low", 12)
# :395 — Exp B lattice success at 0 / 1 / 5 % per-coefficient error (evidence/bkz_results.json, 64-coefficient block-size-2 arm)
_bk = json.load(open(REPO / "evidence/bkz_results.json"))["results"]
def _rate(err):
    _rows = [r for r in _bk if r["block_size"] == 2 and r["num_coefficients"] == 64 and abs(r["error_rate"] - err) < 1e-9]
    assert len(_rows) in (50, 100), (err, len(_rows)); return sum(1 for r in _rows if r["success"]) / len(_rows)
assert (_rate(0.0), _rate(0.01), _rate(0.05)) == (1.0, 0.47, 0.06), (_rate(0.0), _rate(0.01), _rate(0.05))
emit("expb_success_pct_at_0pct_error", f"{_rate(0.0):.0%}"); emit("expb_success_pct_at_1pct_error", f"{_rate(0.01):.0%}"); emit("expb_success_pct_at_5pct_error", f"{_rate(0.05):.0%}")
# :971 — the corrected-stimulus butterfly SNR (rtl final_results.json B_corrected)
_fr = json.load(open(REPO / "experiments/rtl/patch-validation/final_results.json"))
_snr_c = _fr["B_corrected"]["n1000"]["Butterfly"]["snr_unmasked"]; assert 0.00095 < _snr_c < 0.00097, _snr_c
emit("expd_butterfly_snr_corrected_stimulus", f"{_snr_c:.5f}")
# :480 — the TVLA masked window
_tv = json.load(open(REPO / "evidence/tvla_results.json")); assert _tv["n_cycles"] == 595 and _tv["masked_end"] == 345 and _fr["A_published"]["masked_end"] == 345
emit("tvla_intt_cycles", 595); emit("tvla_masked_window_end", 345)
# :331 / :484 / :551 — the RSI enumeration count, the corrected-stimulus budget, the coefficient entropy
assert 2 ** 9 == 512; emit("rsi_enumeration_runs", 512)
_mp = json.load(open(REPO / "evidence/margin_propagation.json"))
def _find_traces(o):
    if isinstance(o, dict):
        for k, v in o.items():
            if k == "traces_full_recovery" and isinstance(v, (int, float)): yield int(v)
            yield from _find_traces(v)
    elif isinstance(o, list):
        for v in o: yield from _find_traces(v)
_tr = sorted(set(_find_traces(_mp))); assert 1156 in _tr and 991 in _tr, _tr
emit("corrected_stimulus_traces_n1000", "1,156"); emit("mldsa_coefficient_entropy_bits", "23.0")
# Exp B rate at 2 %; the converged cap-120 seeds' iteration range; the published-basis budget
emit("expb_success_pct_at_2pct_error", f"{_rate(0.02):.0%}"); assert _rate(0.02) == 0.34
_cv120 = [r["bp_iterations"] for r in _c120 if r["converged"]]; assert len(_cv120) == 9 and max(_cv120) == 119 and min(_cv120) == 65, sorted(_cv120)
emit("nc3_5k_cap120_converged_iters_max", max(_cv120)); emit("nc3_5k_cap120_unconverged", 36 - len(_cv120))
emit("published_basis_traces_n1000", 991)
_cr = [r for r in rr if r.get("snr_n") == 5000 and len(r.get("layers", [])) == 4 and max(b - a for a, b in zip(sorted(r["layers"]), sorted(r["layers"])[1:])) - 1 >= 3]
assert len(_cr) == 52 and not any(r["full_key"] for r in _cr), (len(_cr), sum(1 for r in _cr if r["full_key"]))
emit("gap3_5k_corrected_reruns_pool", f"0/{len(_cr)}")
# Table 8c caption / change list: the gap=1 baseline's full-key rate at 3,000 (TOP-Bc re-run, eff_sweep: 9/10)
assert sum(1 for r in sp3k if r["full_key"]) == 9 and len(sp3k) == 10
emit("baseline_3000_fk_pct_rounded", f"{sum(1 for r in sp3k if r['full_key']) / len(sp3k):.0%}")
# ---- every corrected-criterion gap>=3 run at 5,000 (results.jsonl 55-cap + the cap-120 re-run); the damping arms
_all_cr = _cr + [r for r in rr if r.get("snr_n") == 5000 and len(r.get("layers", [])) == 2 and max(b - a for a, b in zip(sorted(r["layers"]), sorted(r["layers"])[1:])) - 1 >= 3] + _c120
assert len(_all_cr) == 96 and not any(r["full_key"] for r in _all_cr), (len(_all_cr), sum(1 for r in _all_cr if r["full_key"]))
emit("gap3_5k_corrected_all_pool", f"0/{len(_all_cr)}")
_dm = json.load(open(REPO / "evidence/damping_sensitivity.json")); _dm = _dm if isinstance(_dm, list) else (_dm.get("results") or _dm.get("arms"))
_d01 = next(e for e in _dm if e["damping"] == 0.1); _d05 = next(e for e in _dm if e["damping"] == 0.5)
_it01 = [s["bp_iterations"] for s in _d01["per_seed"]]; _it05 = [s["bp_iterations"] for s in _d05["per_seed"]]
assert (min(_it01), max(_it01), _d01["n_full_key"], _d01["n_seeds"]) == (16, 18, 5, 5) and set(_it05) == {30} and (_d05["n_full_key"], _d05["n_seeds"]) == (4, 5)
emit("damping_0p1_iters_min", min(_it01)); emit("damping_0p1_iters_max", max(_it01)); emit("damping_0p5_cap", 30); emit("damping_0p5_full_key", f"{_d05['n_full_key']}/{_d05['n_seeds']}"); emit("damping_0p1_full_key", f"{_d01['n_full_key']}/{_d01['n_seeds']}")

# ---- the no-L1 5,000 arm's cap vs the L1 control; the c6 framing ladder's run configuration; Exp C's noise level and its sigma=2 arm;
#      the full-SNR trace count; the no-L1 50k configuration count; Exp F's two operating points; Exp B's archived BKZ-20 arm; the Exp D acquisition
_g5 = [r for r in rr if r.get("group") == "k4_noL1_5k"]; assert len(_g5) == 75 and {r["max_iter"] for r in _g5} == {40}
_g5cap = sum(1 for r in _g5 if r["bp_iterations"] == r["max_iter"]); assert _g5cap == 20 and sum(1 for r in _g5 if r["converged"]) == 55 and sum(1 for r in _g5 if r["full_key"]) == 7
emit("k4_noL1_5k_cap", 40); emit("k4_noL1_5k_n", len(_g5)); emit("k4_noL1_5k_at_cap_unconverged", _g5cap)
_c5 = [r for r in rr if r.get("group") == "k4_L1_ctrl" and r.get("snr_n") == 5000]; assert len(_c5) == 110 and all(r["converged"] for r in _c5) and {r["max_iter"] for r in _c5} == {60, 100}
emit("k4_L1_ctrl_5k_cap_min", min(r["max_iter"] for r in _c5)); emit("k4_L1_ctrl_5k_cap_max", max(r["max_iter"] for r in _c5))
_lad = [json.loads(l) for l in open(HERE / "c6_framing_ladder_2026-07-27.jsonl") if l.strip()]
assert len(_lad) == 15 and all(r["convergence_tol"] == -1.0 and r["max_iter"] == 60 == r["bp_iterations"] and r["converged"] is False for r in _lad)
import collections as _co; assert _co.Counter(r["snr_n"] for r in _lad) == {50000: 5, 100000: 5, 500000: 5}
emit("ladder_fixed_iters", 60); emit("ladder_seeds_per_budget", 5)
_so = json.load(open(REPO / "evidence/experiments/rsi_vs_rp/shuffling_overhead.json"))["config_results"]
_row = lambda sn, sb, m: next(r for r in _so if r["sigma_noise"] == sn and r["sigma_bias"] == sb and r["mode"] == m)
assert _row(1.0, 0.5, "rsi")["overhead_median"] == 1.25 and _row(1.0, 0.3, "rsi")["overhead_median"] == 7.333333333333333
_r2 = _row(2.0, 1.0, "rsi")["overhead_median"]; _rp2 = _row(2.0, 1.0, "rp")["overhead_median"]; assert _r2 == 1.375 and _rp2 == 4096.0
emit("expc_sigma_noise_reported", "1.0"); emit("expc_sigma2_ratio05_rsi_overhead", f"{_r2:.2f}"); emit("expc_sigma2_ratio05_rp_over_rsi", f"{round(_rp2 / _r2):,}")
_mi_full = 3 * sum(0.5 * math.log2(1 + s) for s in (0.0027, 0.0155, 0.0033)); assert math.ceil(23.0 / _mi_full) == 498
emit("full_snr_traces_n1000", math.ceil(23.0 / _mi_full))
_g50 = [r for r in rr if r.get("group") == "k4_noL1_50k"]; _cf = _co.defaultdict(list); [_cf[r["config"]].append(r["full_key"]) for r in _g50]
assert len(_cf) == 15 and sum(1 for v in _cf.values() if any(v)) == 12 and sum(1 for v in _cf.values() if all(v)) == 10
emit("noL1_k4_50k_configs_any_seed", sum(1 for v in _cf.values() if any(v)))
_ef = json.load(open(REPO / "evidence/exp_f_2layer_bp.json")); _efp = _ef if isinstance(_ef, list) else (_ef.get("results") or _ef.get("points") or _ef.get("operating_points"))
_efs = sorted({p["snr_n"] for p in _efp}); assert 300 in _efs and 10000 in _efs, _efs
emit("expf_lower_point_snr_n", 300); emit("expf_upper_point_snr_n_pow", "10^4")
_bk = json.load(open(REPO / "evidence/bkz_results.json")); _bkr = _bk["results"]; _ag = _co.defaultdict(lambda: [0, 0])
for r in _bkr: k = (r["num_coefficients"], r["block_size"], r["error_rate"]); _ag[k][0] += int(bool(r["success"])); _ag[k][1] += 1
assert _ag[(64, 20, 0.0)] == [20, 20] and _ag[(64, 20, 0.05)] == [1, 30] and _ag[(48, 2, 0.0)] == [19, 50] and {k[0] for k in _ag if k[1] == 20} == {64}
emit("expb_bkz20_block_size", 20); emit("expb_bkz20_64_err0", "20/20"); emit("expb_bkz20_64_err5pct", "1/30"); emit("expb_48_err0", "19/50"); emit("expb_48_err0_pct", "38%")
_fin = (REPO / "experiments/rtl/patch-validation/final.py").read_text(); _N = int(re.search(r"^N = (\d+)", _fin, re.M).group(1)); assert _N == 10000
emit("rtl_traces_per_set", f"{_N:,}"); emit("rtl_traces_total", f"{2 * _N:,}")

_tv = json.load(open(REPO / "evidence/tvla_results.json")); assert (_tv["n_fixed"], _tv["n_random"], _tv["n_cycles"], _tv["masked_end"]) == (1000, 1000, 595, 345)
emit("tvla_n_small", f"{_tv['n_fixed']:,}"); emit("tvla_n_cycles", _tv["n_cycles"]); emit("tvla_masked_end_cycle", _tv["masked_end"]); emit("tvla_unmasked_cycles_measured", _tv["n_cycles"] - _tv["masked_end"])
# F3 (14/15, unarchived q=97 series; count from v2:661) Wilson 95% interval at full precision
def _wilson(k, n, z=1.959963984540054):
    p = k / n; d = 1 + z * z / n; c = (p + z * z / (2 * n)) / d; h = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / d; return c - h, c + h
_lo, _hi = _wilson(14, 15); assert f"{_lo:.1%}" == "70.2%" and f"{_hi:.1%}" == "98.8%", (_lo, _hi)
emit("f3_wilson_lo_14_of_15", f"{_lo:.1%}"); emit("f3_wilson_hi_14_of_15", f"{_hi:.1%}")
# ---- the first cycle after the masking window, ONE-BASED (masked_end + 1; the record's zero-based first unmasked index is 345 --
#      the manuscript says "the last 250 of the 595 cycles" and binds 250/595), and the number of fully unmasked hardware rounds
#      after it, read from the harness record (run_0000.bin: 32-byte header, then one 28-byte record per cycle: cycle u16, mask u8,
#      rounds_count u8, read/write FSM u8 x2, bf_enable u8, pad u8, ten u16 HW/HD fields). The per-run binaries are not in this
#      repository (evidence/rtl_leakage_acquisition.json records their digests), so the record-level checks run only when the
#      companion trace set is present, and the rounds count is then reported on stdout rather than emitted.
import os as _os, struct as _st
emit("tvla_unmasked_first_cycle", _tv["masked_end"] + 1)
_bin = _os.path.expanduser("~/qanary/evidence/experiments/rtl_leakage/fixed/run_0000.bin")
if _os.path.exists(_bin):
    _rec = open(_bin, "rb").read()[32:]
    assert len(_rec) % 28 == 0
    _cyc = [_st.unpack_from("<HBBBBBB", _rec, i * 28) for i in range(len(_rec) // 28)]   # (cycle, mask, rounds_count, rfsm, wfsm, bfen, pad)
    assert len(_cyc) == _tv["n_cycles"] == 595 and [c[0] for c in _cyc] == list(range(595))
    assert all(c[1] == 1 for c in _cyc[:_tv["masked_end"]]) and all(c[1] == 0 for c in _cyc[_tv["masked_end"]:]), "the mask does not drop at cycle 345"
    assert all(c[2] == 0 for c in _cyc[:344]), "rounds_count is not zero throughout the masked window"
    _after = sorted({c[2] for c in _cyc[_tv["masked_end"]:593]}); assert _after == [1, 2, 3], _after
    print(f"companion trace set present: tvla_fully_unmasked_rounds = {len(_after)} (record-level checks passed)")
else:
    print("companion trace set absent: record-level TVLA checks skipped")
# ---- the archived convergence trials fall into two per-run wall-clock regimes at equal graph and iteration counts
_cv = json.load(open(REPO / "evidence/convergence_results.json")); assert len(_cv) == 15
_fast = [t for t in _cv if t["time_s"] / t["bp_iterations"] < 60]; _slow = [t for t in _cv if t["time_s"] / t["bp_iterations"] >= 60]
assert len(_fast) == 3 and len(_slow) == 12 and {t["snr_n"] for t in _fast} == {3000, 5000, 10000} == {t["snr_n"] for t in _slow}
emit("convergence_fast_regime_trials", len(_fast)); emit("convergence_slow_regime_trials", len(_slow))
emit("convergence_fast_regime_minutes_min", f"{min(t['time_s'] for t in _fast) / 60:.0f}"); emit("convergence_fast_regime_minutes_max", f"{max(t['time_s'] for t in _fast) / 60:.0f}")
emit("convergence_slow_regime_minutes_min", f"{min(t['time_s'] for t in _slow) / 60:.0f}"); emit("convergence_slow_regime_minutes_max", f"{max(t['time_s'] for t in _slow) / 60:.0f}")
_hf = 512 * round(max(t["time_s"] for t in _fast) / 60) / 60 / 6; assert 29 <= _hf <= 31, _hf
emit("enumeration_512_runs_6core_hours_fast_regime", f"{_hf:.0f}")
emit("convergence_trials_n", len(_cv))
# ---- every L1-observing four-layer run at 5,000 in the corrected re-derivation, its caps, and the
#      gap>=3 subset (the only unconverged runs); the L1--L4 5,000 point of the consecutive-layer ladder is the corrected-criterion re-derivation
_gap = lambda Ls: max(b - a for a, b in zip(sorted(Ls), sorted(Ls)[1:])) - 1
_k4L1 = [r for r in rr if r.get("snr_n") == 5000 and len(r.get("layers", [])) == 4 and 1 in r["layers"]]
_g3 = [r for r in _k4L1 if _gap(r["layers"]) >= 3]; _rest = [r for r in _k4L1 if _gap(r["layers"]) < 3]
assert len(_k4L1) == 202 and len(_g3) == 52 and {r["max_iter"] for r in _g3} == {55} and not any(r["converged"] for r in _g3) and all(r["converged"] for r in _rest)
assert len({r["config"] for r in _g3}) == 3 and {r["max_iter"] for r in _k4L1} == {55, 60, 100}
emit("k4_L1_5k_runs", len(_k4L1)); emit("k4_L1_5k_cap_min", min(r["max_iter"] for r in _k4L1)); emit("k4_L1_5k_gap3_sets", len({r["config"] for r in _g3}))
emit("k4_L1_5k_gap3_runs", len(_g3)); emit("k4_L1_5k_gap3_cap", 55); emit("k4_L1_5k_gap3_converged", sum(bool(r["converged"]) for r in _g3))
_l1234 = [r for r in _c5 if sorted(r["layers"]) == [1, 2, 3, 4]]; assert len(_l1234) == 5 and all(r["converged"] and r["max_iter"] == 60 for r in _l1234)
emit("ladder_5k_rederivation_iters_min", min(r["bp_iterations"] for r in _l1234)); emit("ladder_5k_rederivation_iters_max", max(r["bp_iterations"] for r in _l1234)); emit("ladder_5k_rederivation_cap", 60)
# ---- the duplicated seed in the corrected re-derivation (records vs distinct seeds);
#      the normalized-efficiency denominator 7 x MI_1-layer across Table 7's operating points
_k4 = [r for r in rr if r.get("snr_n") == 5000 and len(r.get("layers", [])) == 4 and r.get("k_total", 7) == 7]
assert len(_k4) == 277 and len({(tuple(sorted(r["layers"])), r["seed"]) for r in _k4}) == 276
_k4L1s = {(tuple(sorted(r["layers"])), r["seed"]) for r in _k4 if 1 in r["layers"]}; assert len(_k4L1s) == 201
emit("k4_L1_5k_distinct_seeds", len(_k4L1s))
_l1357 = [r for r in rr if r.get("snr_n") == 5000 and sorted(r.get("layers", [])) == [1, 3, 5, 7]]; assert len(_l1357) == 25 and len({r["seed"] for r in _l1357}) == 24
emit("l1357_5k_records", len(_l1357)); emit("l1357_5k_distinct_seeds", len({r["seed"] for r in _l1357}))
_swp = json.load(open(REPO / "evidence/sweep_results.json")); _swp = _swp if isinstance(_swp, list) else (_swp.get("results") or _swp.get("sweep") or _swp.get("points"))
_den = [7 * p["mi_1_layer"] for p in _swp]; assert _den == sorted(_den) and len(_den) == 8
emit("sweep_7x_mi1layer_min", f"{min(_den):.1f}"); emit("sweep_7x_mi1layer_max", f"{max(_den):.1f}")
dest = HERE / "derived_literals.txt"
dest.write_text("\n".join(out) + "\n")
print("\n".join(out[3:])); print(f"wrote {dest.relative_to(REPO)}")
