#!/usr/bin/env python3
"""Emit the Wilson 95% bounds the manuscript prints for small (k, n) at FULL precision (2026-09-02).

The manuscript re-rounded artifact fields that are themselves stored
to four decimals: sweep_results.json stores the 10/10 interval as [0.7225, 1], which re-rounds to 72.3%,
while Wilson(10,10) at full precision is 72.2467% -> 72.2% (the convention every pooled Table 8 cell
already follows, e.g. Wilson(30,30) = 88.6487% -> 88.6%). Likewise Wilson(2,8) = 7.1479% -> 7.1%, not 7.2%.
Fails closed if any stored artifact interval disagrees
with the full-precision value by more than its own 4-decimal rounding.

Run:  python3 paper/arxiv/v3_correction_evidence/build_wilson_literals.py
"""
import json, math, pathlib

REPO = pathlib.Path(__file__).resolve().parents[3]
Z = 1.959963985


def wilson(k, n, z=Z):          # identical to build_table8_pooled_rows.py
    p = k / n
    den = 1 + z * z / n
    centre = (p + z * z / (2 * n)) / den
    half = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / den
    return 100 * (centre - half), 100 * (centre + half)


def pct(v):
    return "0%" if v <= 0 else ("100%" if v >= 100 else f"{v:.1f}%")


pairs = [(10, 10), (15, 15), (2, 8)]
# artifact cross-check: sweep_results.json stores the 10/10 interval to 4 dp
sweep = json.loads((REPO / "evidence/sweep_results.json").read_text())
stored = {r["snr_n"]: r["wilson_ci_95_100pct"] for r in sweep if r["n_trials"] == 10 and r["n_100pct_bsr"] == 10}
lo, _ = wilson(10, 10)
for sn, (slo, shi) in stored.items():
    assert abs(100 * slo - lo) < 0.005 + 1e-9, (sn, slo, lo)   # stored value is the 4-dp rounding of lo
out = ["# Wilson 95% bounds at full precision -- generated by build_wilson_literals.py (2026-09-02)",
       f"# z = {Z}; printed at 1 dp from full precision (the manuscript's convention for pooled Table 8 cells).",
       "# sweep_results.json stores the 10/10 interval as [0.7225, 1] (4 dp); re-rounding that gives 72.3%, the",
       "# full-precision value is 72.2467% -> 72.2%. Exactly one numeric token per value line.", ""]
for k, n in pairs:
    a, b = wilson(k, n)
    out += [f"## Wilson({k},{n}) = [{a:.4f}%, {b:.4f}%]",
            f"wilson_{k}_of_{n}_lo_pct = {pct(a)}",
            f"wilson_{k}_of_{n}_hi_pct = {pct(b)}", ""]
dest = REPO / "paper/arxiv/v3_correction_evidence/wilson_literals.txt"
dest.write_text("\n".join(out) + "\n")
print("\n".join(out)); print(f"wrote {dest.relative_to(REPO)}")
