#!/usr/bin/env python3
"""Emit Table 7's normalized-efficiency quotients as literals.

The quotient has a real primary source: `evidence/sweep_results.json`, the Table 7 run,
which carries `mi_bp` and `mi_1_layer` per operating point. Normalized efficiency is
MI_BP / (7 x MI_1-layer) -- BP's extraction against the 7-layer independent-channel upper
bound, defined at source.md:831.

Both printed figures are real and belong to DIFFERENT operating points:
    10.5824 / (7 x 4.7283) = 0.3197 -> 0.32 at SNR*N = 1,000 (the PEAK)
    11.6479 / (7 x 5.5208) = 0.3014 -> 0.30 at SNR*N = 3,000 (the THRESHOLD)

Regenerate:  python3 build_table7_normalized_efficiency.py
"""
import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[2]  # v3_correction_evidence -> arxiv -> paper -> <repo root>
SRC = ROOT / "evidence" / "sweep_results.json"
OUT = HERE / "table7_normalized_efficiency.txt"

N_LAYERS = 7  # the independent-channel bound Table 7 normalizes against (source.md:831)

rows = sorted(json.loads(SRC.read_text()), key=lambda e: e["snr_n"])
eff = {e["snr_n"]: e["mi_bp"] / (N_LAYERS * e["mi_1_layer"]) for e in rows}
gain = {e["snr_n"]: e["bp_gain"] for e in rows}

assert len(rows) == 8, f"Table 7 has {len(rows)} operating points, not 8"
# The two printed figures.
assert f"{eff[1000]:.2f}" == "0.32", f"peak normalized efficiency is {eff[1000]:.4f}"
assert f"{eff[3000]:.2f}" == "0.30", f"threshold normalized efficiency is {eff[3000]:.4f}"
# The peak really is the peak -- otherwise "peak" in the manuscript means something else.
assert max(eff, key=eff.get) == 1000, f"normalized efficiency peaks at {max(eff, key=eff.get)}"
assert max(gain, key=gain.get) == 1000, f"BP gain peaks at {max(gain, key=gain.get)}"
# Peak gain and threshold efficiency are NOT at the same operating point.
assert gain[1000] != gain[3000], "peak and threshold BP gain coincide"
assert f"{eff[10000]:.2f}" == "0.26", f"ceiling normalized efficiency is {eff[10000]:.4f}"

lines = [
    "# Table 7 normalized efficiency = MI_BP / (7 x MI_1-layer) -- generated by",
    "# build_table7_normalized_efficiency.py from evidence/sweep_results.json.",
    "# Exactly one numeric token per value line.",
    "",
    "# THE PEAK: SNR*N = 1,000. BP gain 2.24x, normalized efficiency:",
    f"table7_normalized_efficiency_at_peak = {eff[1000]:.2f}",
    "",
    "# THE RECOVERY THRESHOLD: SNR*N = 3,000. BP gain 2.11x, normalized efficiency:",
    f"table7_normalized_efficiency_at_threshold = {eff[3000]:.2f}",
    "",
    "# THE CEILING: SNR*N = 10,000, where numerator and denominator both saturate:",
    f"table7_normalized_efficiency_at_ceiling = {eff[10000]:.2f}",
    "",
    "# per operating point (snr_n, MI_BP, MI_1-layer, BP gain, normalized efficiency)",
]
for e in rows:
    lines.append(
        f"#   {e['snr_n']:>6}  {e['mi_bp']:>8}  {e['mi_1_layer']:>8}  "
        f"{e['bp_gain']:>5}x  {eff[e['snr_n']]:.6f}"
    )
OUT.write_text("\n".join(lines) + "\n")
print("\n".join(lines))
