#!/usr/bin/env python3
"""Read the Exp F / Exp H generators and emit the trial geometry the manuscript states at 4.8 (2026-09-02).

source.md's paragraph on stochastic experiments ("Experiments A, D, E, and G are deterministic ...")
describes the generators' seeding. Earlier versions described Exp F as 10 trials x 7 points with base
seed 42 and Exp H's seed as 1000*trial + snr_n mod 1000; neither matched the code. This file is read from the GENERATORS, not from prose.

Fails closed if any expected pattern is missing from the generator source, or if the artifacts on disk
do not have the geometry the generators declare.

Run:  python3 paper/arxiv/v3_correction_evidence/build_generator_metadata.py
"""
import json, pathlib, re

REPO = pathlib.Path(__file__).resolve().parents[3]
F = (REPO / "experiments/exp_f_2layer_bp.py").read_text()
H = (REPO / "experiments/exp_h_monte_carlo.py").read_text()


def grab(pat, src, what):
    m = re.search(pat, src, re.M)
    assert m, f"pattern for {what} not found"
    return m


f_points = grab(r"^\s*snr_n_values\s*=\s*\[([^\]]+)\]", F, "Exp F points").group(1)
f_points = [int(x) for x in f_points.split(",")]
f_seeds = int(grab(r"^\s*n_seeds\s*=\s*(\d+)", F, "Exp F n_seeds").group(1))
f_seed = grab(r"seed\s*=\s*s\s*\*\s*(\d+)\s*\+\s*int\(snr_n\)", F, "Exp F seed formula")
h_trials = int(grab(r"^N_TRIALS\s*=\s*(\d+)", H, "Exp H N_TRIALS").group(1))
h_points = [int(x) for x in grab(r"^SNR_N_VALUES\s*=\s*\[([^\]]+)\]", H, "Exp H points").group(1).split(",")]
h_seed = grab(r"seed\s*=\s*t\s*\*\s*([\d_]+)\s*\+\s*int\(snr_n\)\s*\+\s*(\d+)", H, "Exp H seed formula")

fa = json.loads((REPO / "evidence/exp_f_2layer_bp.json").read_text())["results"]
ha = json.loads((REPO / "evidence/exp_h_monte_carlo.json").read_text())["results"]
assert [r["snr_n"] for r in fa] == f_points and all(r["n_seeds"] == f_seeds for r in fa), "Exp F artifact geometry"
assert [r["snr_n"] for r in ha] == h_points and all(r["n_trials"] == h_trials for r in ha), "Exp H artifact geometry"
assert not any("ci" in k.lower() for k in fa[0]), "Exp F artifact unexpectedly carries a CI field"
assert "wilson_ci_above_50pct" in ha[0], "Exp H artifact lacks its Wilson CI"

out = ["# Exp F / Exp H generator metadata -- generated by build_generator_metadata.py (2026-09-02)",
       "# read from experiments/exp_f_2layer_bp.py and experiments/exp_h_monte_carlo.py; checked against the",
       "# artifacts' geometry. Exactly one numeric token per value line.", "",
       f"exp_f_seeds_per_point = {f_seeds}",
       f"exp_f_points = {len(f_points)}",
       f"exp_f_seed_multiplier = {int(f_seed.group(1))}",
       f"exp_f_reports_ci = 0",
       f"exp_h_trials_per_point = {h_trials}",
       f"exp_h_points = {len(h_points)}",
       f"exp_h_seed_multiplier = {int(h_seed.group(1).replace('_', ''))}",
       f"exp_h_seed_offset = {int(h_seed.group(2))}"]
dest = REPO / "paper/arxiv/v3_correction_evidence/generator_metadata.txt"
dest.write_text("\n".join(out) + "\n")
print("\n".join(out))
print(f"wrote {dest.relative_to(REPO)}")
